// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:95c9e7a0-f922-4647-b6a4-2673772cd7b4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_r43MpRAEo",
    "aws_user_pools_web_client_id": "hnod4vkf1ak24cecvdqt4ret2",
    "oauth": {},
    "REGION": "us-east-2",
    "USER_POOL_ID": "us-east-2_SF2DCPO5Y",
    "APP_CLIENT_ID": "617jkna9pqeg8rmgtg9uv4e6j4",
    "IDENTITY_POOL_ID": "",     
    "UserPoolId": "us-east-2_SF2DCPO5Y",
    "ClientId": "617jkna9pqeg8rmgtg9uv4e6j4"
};


export default config;
